[package]
name = "interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
git2 = "0.18.3"
thiserror = "1.0.58"
once_cell = "1.19.0"
dirs = "5.0.1"
